version: '3.8'

services:
  # Servidor Web (Tu ventana al mundo)
  web:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./services/nginx/conf.d:/etc/nginx/conf.d
      - ./services/web:/usr/share/nginx/html
    depends_on:
      - node

  # API (El cerebro en Node.js)
  node:
    build: ./services/node
    ports:
      - "3000:3000"
    volumes:
      - ./services/node:/usr/src/app
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres

  # Base de Datos (El archivador de Tanenbaum)
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Administrador de DB (La interfaz visual)
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: maria.gonzalez.r@correounivalle.edu.co
      PGADMIN_DEFAULT_PASSWORD: 12345
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data:
